# ==========================================================
# FILE: app/services/excel_import_service.py (PRODUCTION v1.0)
# PURPOSE: Production-grade Excel parsing and database import service
# ==========================================================

import logging
from datetime import datetime, date
from typing import Dict, Any, List, Optional

from openpyxl import load_workbook
from sqlalchemy.orm import Session

from app.models import DeliveryReport

# Initialize logger
logger = logging.getLogger(__name__)

# ==========================================================
# CUSTOM EXCEPTIONS
# ==========================================================

class ExcelImportServiceError(Exception):
    """Base exception for Excel import service errors."""
    pass

class VerificationError(Exception):
    """Raised when the Excel file fails verification (e.g., missing columns)."""
    pass

# ==========================================================
# HELPER FUNCTIONS
# ==========================================================

def _clean_string(value: Any) -> Optional[str]:
    """Clean and strip string values."""
    if value is None:
        return None
    if isinstance(value, str):
        cleaned = value.strip()
        return cleaned if cleaned else None
    return str(value)

def _safe_float(value: Any) -> Optional[float]:
    """Safely convert a value to float."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (ValueError, TypeError):
        return None

def _safe_int(value: Any) -> Optional[int]:
    """Safely convert a value to integer."""
    if value is None or value == "":
        return None
    try:
        return int(value)
    except (ValueError, TypeError):
        return None

def _parse_date_from_excel(value: Any) -> Optional[date]:
    """
    Parse date from Excel. Handles strings, datetime objects, and Excel date floats.
    """
    if value is None or value == "":
        return None
    
    # If it's already a datetime or date object
    if isinstance(value, (datetime, date)):
        return value.date() if isinstance(value, datetime) else value

    # If it's a string, attempt to parse it (YYYY-MM-DD, MM/DD/YYYY, etc.)
    if isinstance(value, str):
        value = value.strip()
        for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%Y%m%d"):
            try:
                return datetime.strptime(value, fmt).date()
            except ValueError:
                continue
        # If parsing fails, log warning
        logger.warning(f"Could not parse date from string: {value}")

    # Excel dates are sometimes stored as floats
    if isinstance(value, (int, float)):
        try:
            # Excel date serial number (days since 1899-12-30)
            from datetime import timedelta
            return (datetime(1899, 12, 30) + timedelta(days=float(value))).date()
        except Exception:
            pass

    return None

# ==========================================================
# CORE IMPORT FUNCTION
# ==========================================================

def import_delivery_excel(
    db: Session,
    file_path: str,
    source_filename: str,
    upload_batch_id: str,
    batch_size: int = 1000
) -> Dict[str, Any]:
    """
    Reads an Excel file, validates data, and bulk inserts valid rows
    into the DeliveryReport table.
    
    Args:
        db: SQLAlchemy database session.
        file_path: Absolute path to the uploaded Excel file.
        source_filename: Original name of the uploaded file.
        upload_batch_id: Unique batch ID generated by the upload router.
        batch_size: Number of records to commit per batch.
    
    Returns:
        Dictionary containing import metrics.
    """
    logger.info(f"Starting import for batch: {upload_batch_id}, file: {source_filename}")
    
    metrics = {
        "rows_read": 0,
        "rows_upserted": 0,
        "rows_failed": 0,
        "rows_valid": 0,
        "batch_id": upload_batch_id,
        "errors": []
    }

    try:
        # Load workbook with data_only=True to get calculated values instead of formulas
        wb = load_workbook(file_path, data_only=True)
        ws = wb.active
    except Exception as e:
        logger.exception(f"Failed to load Excel file: {file_path}")
        raise ExcelImportServiceError(f"Failed to read Excel file: {str(e)}")

    # Extract headers (assumes first row is headers)
    headers = []
    for cell in ws[1]:
        if cell.value is not None:
            headers.append(_clean_string(cell.value).upper())
        else:
            headers.append(None)

    # Map expected headers to column indices (case-insensitive)
    column_map = {}
    for expected in ["DN NO", "MATERIAL NO", "CUSTOMER NAME", "DN CREATE DATE", 
                     "GOOD ISSUE DATE", "POD DATE", "DN QTY", "DN AMOUNT", "WAREHOUSE"]:
        # Try to find exact or partial match
        found = False
        for i, h in enumerate(headers):
            if h and expected in h:
                column_map[expected] = i
                found = True
                break
        if not found:
            raise VerificationError(f"Required column '{expected}' not found in Excel file header.")

    # Initialize records list
    records_to_insert = []
    errors = []

    # Iterate through data rows (starting from row 2)
    for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
        metrics["rows_read"] += 1
        
        try:
            # Safely extract data using column_map
            dn_no = _clean_string(row[column_map["DN NO"]])
            if not dn_no:
                raise ValueError("DN No is empty or missing")

            material_no = _clean_string(row[column_map["MATERIAL NO"]])
            customer_name = _clean_string(row[column_map["CUSTOMER NAME"]])
            warehouse = _clean_string(row[column_map["WAREHOUSE"]])
            
            dn_create_date = _parse_date_from_excel(row[column_map["DN CREATE DATE"]])
            good_issue_date = _parse_date_from_excel(row[column_map["GOOD ISSUE DATE"]])
            pod_date = _parse_date_from_excel(row[column_map["POD DATE"]])

            dn_qty = _safe_int(row[column_map["DN QTY"]])
            dn_amount = _safe_float(row[column_map["DN AMOUNT"]])

            # Create the DeliveryReport instance
            report = DeliveryReport(
                dn_no=dn_no,
                material_no=material_no,
                customer_name=customer_name,
                warehouse=warehouse,
                dn_create_date=dn_create_date,
                good_issue_date=good_issue_date,
                pod_date=pod_date,
                dn_qty=dn_qty,
                dn_amount=dn_amount,
                source_file=source_filename,
                upload_batch_id=upload_batch_id,
                # Default statuses as per the model
                delivery_status="Pending",
                pgi_status="Pending" if not good_issue_date else "Completed",
                pod_status="Pending" if not pod_date else "Completed",
                pending_flag=True if not pod_date else False
            )

            records_to_insert.append(report)
            metrics["rows_valid"] += 1

        except Exception as e:
            logger.warning(f"Row {row_idx} failed validation: {e}")
            errors.append({"row": row_idx, "error": str(e)})
            metrics["rows_failed"] += 1

    # Perform bulk insert in batches to manage memory
    if records_to_insert:
        try:
            # Convert objects to dictionaries for bulk_insert_mappings
            records_dict = [
                {
                    "dn_no": r.dn_no,
                    "material_no": r.material_no,
                    "customer_name": r.customer_name,
                    "warehouse": r.warehouse,
                    "dn_create_date": r.dn_create_date,
                    "good_issue_date": r.good_issue_date,
                    "pod_date": r.pod_date,
                    "dn_qty": r.dn_qty,
                    "dn_amount": r.dn_amount,
                    "source_file": r.source_file,
                    "upload_batch_id": r.upload_batch_id,
                    "delivery_status": r.delivery_status,
                    "pgi_status": r.pgi_status,
                    "pod_status": r.pod_status,
                    "pending_flag": r.pending_flag
                }
                for r in records_to_insert
            ]

            # Bulk insert mapping
            db.bulk_insert_mappings(DeliveryReport, records_dict)
            db.flush()
            
            metrics["rows_upserted"] = len(records_to_insert)
            logger.info(f"Successfully inserted {metrics['rows_upserted']} records into delivery_reports.")

        except Exception as e:
            logger.exception("Failed to bulk insert records.")
            db.rollback()
            raise ExcelImportServiceError(f"Database insert failed: {str(e)}")

    else:
        logger.info("No valid records found to insert.")

    # Append simplified errors to the metrics
    metrics["errors"] = [f"Row {err['row']}: {err['error']}" for err in errors]
    
    logger.info(f"Import completed for batch {upload_batch_id}. "
                f"Read: {metrics['rows_read']}, "
                f"Inserted: {metrics['rows_upserted']}, "
                f"Failed: {metrics['rows_failed']}")

    return metrics
